### PR TITLE
Fix reactive declarations in TypeScript

### LINKED ISSUE #167: Problem with Typescript and reactive declaration, "Unresolved variable or type"
When using "lang='ts'" in the script tag, i am supposing that intellij wont recognize svelte syntax `$:` and throw the message bellow:

Screenshot from 2020-10-20 11-25-43

If that behavior does not come from the svelte plugin just ignore this issue and forgive me for the missundertood.

### PR DESCRIPTION
**Pull request by tomblachut**
Fixes #167. I only did quick checkup, need to do more regression testing before merging, I don't have more time now unfortunately.

@anstarovoyt how bad do you think this solution is? I though maybe you could change actual `TypeScriptReferenceExpressionResolver` a bit in WS 2020.3 so this `TypeScriptReferenceExpressionResolver2` could be deleted later.

### CODE REVIEW

File: src/main/java/dev/blachut/svelte/lang/codeInsight/TypeScriptReferenceExpressionResolver2.java [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+            return true;
+        } else {
+            return results != null && results.length != 0 ? false : this.isGlobalThis();
+        }
+    }
+
+    private ResolveResult[] doResolveReference(boolean incompleteCode) {
+        assert this.myReferencedName != null;
+
+        TypeScriptResolveProcessor<ResolveResultSink> localProcessor = (TypeScriptResolveProcessor) createLocalResolveProcessor(new ResolveResultSink(this.myRef, this.myReferencedName, false, incompleteCode));
```
Comment (tomblachut) [inline src/main/java/dev/blachut/svelte/lang/codeInsight/TypeScriptReferenceExpressionResolver2.java:95]: this is actual change, rest is copypaste of private stuff

**Comment by anstarovoyt** [comment]
I will take a look on Friday, but in general, I have a couple different ideas: 
1. We have an extension point to contribute new references (and resolution for ref. expression)
2. We have some methods in FrameworkIndexingHandler that allows contributing new elements in the resolution

**Comment by tomblachut** [comment]
okay, sounds definitely better

**Comment by anstarovoyt** [comment]
Ok, I spent some time investigating the problem, and looks like the simplest solution is
```
   class SvelteTypeScriptReferenceExpressionResolver(...

    override fun resolve(expression: JSReferenceExpressionImpl, incompleteCode: Boolean): Array<ResolveResult> {
        val resolveImplicits = resolveImplicits(expression)
        if (resolveImplicits.isNotEmpty()) return resolveImplicits

        val resolved = super.resolve(expression, incompleteCode)
        if (resolved.size == 0 && expression.qualifier == null) {
            val sink = ResolveResultSink(myRef, myReferencedName, false, incompleteCode)
            val localProcessor = createLocalResolveProcessor(sink)
            JSReferenceExpressionImpl.doProcessLocalDeclarations(myRef,myQualifier, localProcessor as ResolveProcessor?, false, false, null as Boolean?)
            val jsElement = (localProcessor as SinkResolveProcessor<*>).result
            val labeledStatement = jsElement.parentOfType<JSLabeledStatement>()
            if (labeledStatement != null && labeledStatement.label == REACTIVE_LABEL) {
                return localProcessor.resultsAsResolveResults
            }
        }
        return resolved
    }

    override fun createLocalResolveProcessor(sink: ResolveResultSink): SinkResolveProcessor<ResolveResultSink> {
        return SvelteReactiveDeclarationsUtil.SvelteSinkResolveProcessor(myReferencedName, myRef, sink)
    }
```
I haven't tried but in general, it should work

**Comment by tomblachut** [comment]
I think this will break if you for some reason shadow a global

e.g. 
```
  $: EventTarget = 1;
```

**Comment by anstarovoyt** [comment]
sounds weired, I'd prefer to keep the solution until the first request :) 
But you can also change the order (first try to check locals). ``doProcessLocalDeclarations``  It is a cheap operation anyway

**Comment by anstarovoyt** [comment]
+ of course, I will change ``TypeScriptReferenceExpressionResolver`` the code on the WS side, but it will land only for 2020.3

**Comment by tomblachut** [comment]
Ok this sounds like a good middle ground 👍  I'll delete copied file and test your snippet later

**Comment by tomblachut** [comment]
@anstarovoyt your snippet works nicely, thanks!
